WIP: Liquid layout
mcode/rems-smart-on-fhir pull request #89
Opened 2024-04-18 12:35 UTC by jtquach1

## Describe your changes

> Please include a summary of the changes and the related issue/task. Please also include relevant motivation and context. List any dependencies that are required for this change, including links to other pull requests/branches in other repositories if applicable.

[Default breakpoints in MUI 5](https://mui.com/material-ui/customization/breakpoints/#default-breakpoints) to reference for below

## Before - Home page with patient view and medication select dropdown
### xs screen  (problematic)
![image](https://github.com/mcode/rems-smart-on-fhir/assets/33106214/5e97e7b7-85bd-4ec8-83ce-139d899cb2c5)
![image](https://github.com/mcode/rems-smart-on-fhir/assets/33106214/8bc1c0f0-0e8b-4efd-92e0-cbb41fdb0bdb)

### sm screen (problematic at breakpoint, but otherwise OK)
![image](https://github.com/mcode/rems-smart-on-fhir/assets/33106214/a6fc0755-2747-45c8-82f4-5ded894ad166)
![image](https://github.com/mcode/rems-smart-on-fhir/assets/33106214/99006e8e-39f1-421d-a66f-f48de030a0d2)

### md screen (OK)
![image](https://github.com/mcode/rems-smart-on-fhir/assets/33106214/a81283ca-7176-4f14-8574-7f988f008c41)
![image](https://github.com/mcode/rems-smart-on-fhir/assets/33106214/6b699018-f703-4e5f-9c98-a512e1171b35)

### lg screen (OK)
![image](https://github.com/mcode/rems-smart-on-fhir/assets/33106214/202ed564-d8f8-44c4-b715-6418ec624327)
![image](https://github.com/mcode/rems-smart-on-fhir/assets/33106214/23db579b-3661-4bc3-8316-e8f5ade0464a)

## Issue ticket number and Jira link

> Please include the Jira Ticket Number and Link for this issue/task.

https://jira.mitre.org/browse/REMS-654

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] Ensure the target / base branch for any feature PR is set to `dev` not main (the only exception to this is releases from `dev` and hotfix branches)

## Checklist for conducting a review
- [ ] Review the code changes and make sure they all make sense and are necessary. 
- [ ] Pull the PR branch locally and test by running through workflow and making sure everything works as it is supposed to. 

## Workflow 

Owner of the Pull Request will be responsible for merge after all requirements are met, including approval from at least one reviewer. Additional changes made after a review will dismiss any approvals and require re-review of the additional updates. Auto merging can be enabled below if additional changes are likely not to be needed. The bot will auto assign reviewers to your Pull Request for you.

2024-05-06 15:20 UTC, jtquach1 commented on public/index.html
> +    <link
prettier

2024-05-17 18:31 UTC, zacharyrobin reviewed
Merge Conflicts need to be addressed

2024-05-17 18:31 UTC, zacharyrobin commented on src/views/Questionnaire/components/RemsInterface/RemsInterface.tsx
>      return bundle.entry?.map(entry => {
This seems to be causing a unique prop key warning. doesnt cause any breaking changes but may want to address this at some point 
![Screenshot 2024-05-17 at 10 59 31 AM](https://github.com/mcode/rems-smart-on-fhir/assets/28585306/f95cef3b-74a4-4776-bce7-5b71c119ad97)
![Screenshot 2024-05-17 at 10 59 35 AM](https://github.com/mcode/rems-smart-on-fhir/assets/28585306/33df1cb3-fe35-42f5-bee1-7e33f05996dd)

2024-05-20 16:23 UTC, KeeyanGhoreshi requested changes
When you load a previous form, then modify it, then try to save it to the ehr, it reverts your form back to the previously loaded version, erasing any progress.

2024-05-20 19:03 UTC, jtquach1 commented
> When you load a previous form, then modify it, then try to save it to the ehr, it reverts your form back to the previously loaded version, erasing any progress.

Thanks for catching that, should be fixed now

2024-05-21 07:28 UTC, KeeyanGhoreshi approved these changes

2024-05-21 13:02 UTC, merged